import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemTransformer;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDict;
/*
val plateArray = [
<advancedrocketry:productplate:1>,
<advancedrocketry:productplate>,
<basemetals:adamantine_plate>,
<basemetals:antimony_plate>,
<basemetals:aquarium_plate>,
<basemetals:bismuth_plate>,
<basemetals:coldiron_plate>,
<basemetals:cupronickel_plate>,
<basemetals:pewter_plate>,
<basemetals:starsteel_plate>,
<hammermetals:chrome_plate>,
<hammermetals:palladium_plate>,
<hammermetals:platiniridium_plate>,
<immersiveengineering:metal:35>,
<libvulpes:productplate:3>,
<modernmetals:aluminumbrass_plate>,
<modernmetals:beryllium_plate>,
<modernmetals:boron_plate>,
<modernmetals:cadmium_plate>,
<modernmetals:chromium_plate>,
<modernmetals:galvanizedsteel_plate>,
<modernmetals:magnesium_plate>,
<modernmetals:manganese_plate>,
<modernmetals:nichrome_plate>,
<modernmetals:plutonium_plate>,
<modernmetals:rutile_plate>,
<modernmetals:stainlesssteel_plate>,
<modernmetals:tantalum_plate>,
<modernmetals:thorium_plate>,
<modernmetals:zirconium_plate>,
<moreplates:alumite_plate>,
<moreplates:ardite_plate>,
<moreplates:awakened_draconium_plate>,
<moreplates:black_quartz_plate>,
<moreplates:coal_plate>,
<moreplates:cobalt_plate>,
<moreplates:conductive_iron_plate>,
<moreplates:crude_steel_plate>,
<moreplates:crystal_matrix_plate>,
<moreplates:crystalline_alloy_plate>,
<moreplates:crystalline_pink_slime_plate>,
<moreplates:dark_steel_plate>,
<moreplates:demon_plate>,
<moreplates:diamond_plate>,
<moreplates:draconium_plate>,
<moreplates:electrical_steel_plate>,
<moreplates:electrotine_alloy_plate>,
<moreplates:elementium_plate>,
<moreplates:emerald_plate>,
<moreplates:enchanted_plate>,
<moreplates:end_steel_plate>,
<moreplates:energetic_alloy_plate>,
<moreplates:energetic_silver_plate>,
<moreplates:evil_infused_iron_plate>,
<moreplates:fiery_plate>,
<moreplates:gaia_spirit_plate>,
<moreplates:inferium_plate>,
<moreplates:infinity_plate>,
<moreplates:insanium_plate>,
<moreplates:intermedium_plate>,
<moreplates:iron_alloy_plate>,
<moreplates:ironwood_plate>,
<moreplates:knightmetal_plate>,
<moreplates:knightslime_plate>,
<moreplates:lapis_lazuli_plate>,
<moreplates:manasteel_plate>,
<moreplates:manyullyn_plate>,
<moreplates:melodic_alloy_plate>,
<moreplates:mirion_plate>,
<moreplates:nether_quartz_plate>,
<moreplates:neutronium_plate>,
<moreplates:osgloglas_plate>,
<moreplates:osmiridium_plate>,
<moreplates:osmium_plate>,
<moreplates:pig_iron_plate>,
<moreplates:prudentium_plate>,
<moreplates:pulsating_iron_plate>,
<moreplates:red_alloy_plate>,
<moreplates:redstone_alloy_plate>,
<moreplates:redstone_plate>,
<moreplates:refined_glowstone_plate>,
<moreplates:refined_obsidian_plate>,
<moreplates:soularium_plate>,
<moreplates:soulium_plate>,
<moreplates:stellar_alloy_plate>,
<moreplates:superium_plate>,
<moreplates:supremium_plate>,
<moreplates:terrasteel_plate>,
<moreplates:vibrant_alloy_plate>,
<moreplates:vivid_alloy_plate>,
<techreborn:plates:12>,
<techreborn:plates:13>,
<techreborn:plates:14>,
<techreborn:plates:15>,
<techreborn:plates:16>,
<techreborn:plates:18>,
<techreborn:plates:2>,
<techreborn:plates:31>,
<techreborn:plates:32>,
<techreborn:plates:33>,
<techreborn:plates:34>,
<techreborn:plates:35>,
<techreborn:plates:36>,
<techreborn:plates:38>,
<techreborn:plates:9>,
<thermalfoundation:material:32>,
<thermalfoundation:material:320>,
<thermalfoundation:material:321>,
<thermalfoundation:material:322>,
<thermalfoundation:material:323>,
<thermalfoundation:material:324>,
<thermalfoundation:material:325>,
<thermalfoundation:material:326>,
<thermalfoundation:material:327>,
<thermalfoundation:material:328>,
<thermalfoundation:material:33>,
<thermalfoundation:material:352>,
<thermalfoundation:material:353>,
<thermalfoundation:material:354>,
<thermalfoundation:material:355>,
<thermalfoundation:material:356>,
<thermalfoundation:material:357>,
<thermalfoundation:material:358>,
<thermalfoundation:material:359>,
] as IItemStack[];


mods.magneticraft.HydraulicPress.addRecipe(<minecraft:snow>, <minecraft:snowball>, 20, 0, true);
*/
for entry in oreDict.entries {                                              // Loop over the whole ore dictionary
    if (!(entry.name has "ingot" || entry.name has "gem")) continue;        // Grabbing only the entries that are either ingots or gems
    if (entry.empty) continue;                                              // We don't want ingots that don't exist (calling `firstItem` with an empty tag results in problems, so better safe than crashing)
    val resourceName = entry.name.replace("ingot", "").replace("gem", "");  // Let's grab the name of the resource
    val plateDict = oreDict.get("plate" ~ resourceName);                    // And then the ore dictionary entry of the plate
    if (plateDict.empty) continue;                                          // If no such plate exists, we skip it
                                                                            // Else we add the recipe:
                                                                            // input = the first Item of the ore dictionary entry for the ingot
                                                                            // output = the first item of the ore dictionary entry for the plate
                                                                            // duration = 1 second -> 20 ticks
                                                                            // mode = 0?
                                                                            // useOreDict = yes, please
    mods.magneticraft.HydraulicPress.addRecipe(entry.firstItem, plateDict.firstItem, 20, 0, true);
}