mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:machineblock2:11>.withTag({tier: 4}), [
	[<extendedcrafting:material:13>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "manasteel", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "liquidfusionfuel", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "cyanite", Amount: 1000}}), <forge:bucketfilled>.withTag({FluidName: "neutron", Amount: 1000}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "osmiridium", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "terrasteel", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "elementium", Amount: 1000}}), <extendedcrafting:material:13>],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "neutron", Amount: 1000}}), <avaritiatweaks:gaia_block>, <extracells:storage.component:10>, <ore:ingotUltimate>, <mysticalagradditions:stuff:69>, <ore:ingotUltimate>, <extracells:storage.component:10>, <avaritiatweaks:gaia_block>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "liquiddeuterium", Amount: 1000}})],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "calcium_sulfate_solution", Amount: 1000}}), <extracells:storage.component:10>, <ore:plateInfinity>, <appliedenergistics2:material:47>, <extendedcrafting:singularity_ultimate>, <tp:octuple_compressed_nether_block>, <ore:plateInfinity>, <extracells:storage.component:10>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "liquidtritium", Amount: 1000}})],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "xu_evil_metal", Amount: 1000}}), <ore:ingotUltimate>, <tp:octuple_compressed_nether_block>, <extrautils2:drum:3>.withTag({BlockEntityTag: {ForgeCaps: {"nuclearcraft:capability_default_radiation_resistance": {radiationResistance: 0.0}}, id: "xu2:tank65536", tank: {FluidName: "glass", Amount: 65536000}}, Fluid: {FluidName: "glass", Amount: 1}, display: {Lore: ["(+NBT)"]}}), <avaritia:endest_pearl>, <extrautils2:drum:3>.withTag({Fluid: {FluidName: "glowstone", Amount: 65536000}}), <appliedenergistics2:material:47>, <ore:ingotUltimate>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}})],
	[<forge:bucketfilled>.withTag({FluidName: "neutron", Amount: 1000}), <mysticalagradditions:stuff:69>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Fluid: {FluidName: "ic2uu_matter", Amount: 500000}, Level: 4 as byte, Lock: 0 as byte}), <avaritia:endest_pearl>, <extendedcrafting:singularity_ultimate>, <mysticalagradditions:stuff:69>, <forge:bucketfilled>.withTag({FluidName: "neutron", Amount: 1000})],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "xu_enchanted_metal", Amount: 1000}}), <ore:ingotUltimate>, <appliedenergistics2:material:47>, <extrautils2:drum:3>.withTag({Fluid: {FluidName: "ender", Amount: 65536000}}), <avaritia:endest_pearl>, <extrautils2:drum:3>.withTag({Fluid: {FluidName: "redstone", Amount: 65536000}}), <tp:octuple_compressed_nether_block>, <ore:ingotUltimate>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "cloud_seed_concentrated", Amount: 1000}})],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "xu_demonic_metal", Amount: 1000}}), <extracells:storage.component:10>, <ore:plateInfinity>, <tp:octuple_compressed_nether_block>, <extendedcrafting:singularity_ultimate>, <appliedenergistics2:material:47>, <ore:plateInfinity>, <extracells:storage.component:10>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "aerotheum", Amount: 1000}})],
	[<extracells:pattern.fluid>.withTag({Fluid: {FluidName: "infinity", Amount: 1000}}), <avaritiatweaks:gaia_block>, <extracells:storage.component:10>, <ore:ingotUltimate>, <mysticalagradditions:stuff:69>, <ore:ingotUltimate>, <extracells:storage.component:10>, <avaritiatweaks:gaia_block>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "petrotheum", Amount: 1000}})],
	[<extendedcrafting:material:13>, <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "mana", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "platinum", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "iridium", Amount: 1000}}), <forge:bucketfilled>.withTag({FluidName: "neutron", Amount: 1000}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "liquid_sunshine", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "cryotheum", Amount: 1000}}), <extracells:pattern.fluid>.withTag({Fluid: {FluidName: "pyrotheum", Amount: 1000}}), <extendedcrafting:material:13>]
]);
mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:table_basic>, [
	[<extendedcrafting:material:9>, <extendedcrafting:material:15>, <extendedcrafting:material:11>],
	[<extendedcrafting:material:16>, <avaritia:extreme_crafting_table>, <extendedcrafting:material:17>],
	[<extendedcrafting:material:10>, <extendedcrafting:material:14>, <extendedcrafting:material:8>]
]);
recipes.addShaped(<avaritia:extreme_crafting_table>, [[<avaritia:double_compressed_crafting_table>, <avaritia:resource:1>, <avaritia:double_compressed_crafting_table>],[<avaritia:resource:1>, <extendedcrafting:storage:2>, <avaritia:resource:1>], [<avaritia:double_compressed_crafting_table>, <avaritia:resource:1>, <avaritia:double_compressed_crafting_table>]]);